"""
strategy_exporter.py — 策略多格式导出
=======================================

将策略配置导出为 Pine Script v6 / MQL5 / 通达信公式。

借鉴 Vibe-Trading 的多格式策略导出功能。

用法:
  from strategy_exporter import export_pine, export_mql5
  print(export_pine("RSI", symbol="BTC/USDT", rsi_period=8, oversold=22, overbought=75))
  print(export_mql5("SMA", symbol="SOL/USDT", fast=10, slow=30, sl=0.03, tp=0.05))
"""

from typing import Dict, Optional


def export_pine(strategy: str, **params) -> str:
    """
    导出 Pine Script v6 策略代码。
    支持: RSI, SMA, BOLLINGER, MACD, DONCHIAN, ATRSTOP
    """
    exporters = {
        "RSI": _pine_rsi,
        "SMA": _pine_sma,
        "BOLLINGER": _pine_bollinger,
        "MACD": _pine_macd,
        "DONCHIAN": _pine_donchian,
        "ATRSTOP": _pine_atrstop,
        "KDJ": _pine_kdj,
    }
    fn = exporters.get(strategy.upper())
    if not fn:
        return f"// 不支持导出 {strategy}（支持: {', '.join(exporters.keys())}）"
    return fn(**params)


def _pine_header(name: str, desc: str, sl: float = 0.03, tp: float = 0.05) -> str:
    return f"""//@version=6
// {name} Strategy — Auto-generated by Trading System
// {desc}

strategy("{name}", overlay=true, initial_capital=10000,
  commission_type=strategy.commission.percent, commission_value=0.1,
  slippage=3)

// === Parameters ===
stop_loss_pct = input.float({sl*100:.1f}, "Stop Loss %", minval=0.1, maxval=20, step=0.1) / 100
take_profit_pct = input.float({tp*100:.1f}, "Take Profit %", minval=0.1, maxval=50, step=0.1) / 100

// === Entry Logic ===
var float entry_price = na"""


def _pine_footer(sl: float = 0.03, tp: float = 0.05) -> str:
    return """
// === Position Management ===
if strategy.position_size > 0
    strategy.exit("SL/TP", "Long", stop=entry_price * (1 - stop_loss_pct),
                  limit=entry_price * (1 + take_profit_pct))

if strategy.position_size < 0
    strategy.exit("SL/TP", "Short", stop=entry_price * (1 + stop_loss_pct),
                  limit=entry_price * (1 - take_profit_pct))

// === Plot ===
plot(close, "Price", color=color.white)
"""


def _pine_rsi(rsi_period: int = 8, oversold: float = 22.0, overbought: float = 75.0,
              sl: float = 0.03, tp: float = 0.05, **kwargs) -> str:
    code = _pine_header("RSI", f"period={rsi_period} oversold={oversold} overbought={overbought}", sl, tp)
    code += f"""
rsi_period = input.int({rsi_period}, "RSI Period", minval=2, maxval=50)
rsi_oversold = input.float({oversold}, "Oversold", minval=5, maxval=50)
rsi_overbought = input.float({overbought}, "Overbought", minval=50, maxval=95)

rsi_val = ta.rsi(close, rsi_period)

long_condition = ta.crossover(rsi_val, rsi_oversold)
short_condition = ta.crossunder(rsi_val, rsi_overbought)

if long_condition
    strategy.entry("RSI Long", strategy.long)
    entry_price := close

if short_condition
    strategy.entry("RSI Short", strategy.short)
    entry_price := close
"""
    code += _pine_footer(sl, tp)
    return code


def _pine_sma(fast_period: int = 10, slow_period: int = 30,
              sl: float = 0.03, tp: float = 0.05, **kwargs) -> str:
    code = _pine_header("SMA Cross", f"fast={fast_period} slow={slow_period}", sl, tp)
    code += f"""
fast_len = input.int({fast_period}, "Fast SMA", minval=2)
slow_len = input.int({slow_period}, "Slow SMA", minval=5)

sma_fast = ta.sma(close, fast_len)
sma_slow = ta.sma(close, slow_len)

long_condition = ta.crossover(sma_fast, sma_slow)
short_condition = ta.crossunder(sma_fast, sma_slow)

if long_condition
    strategy.entry("SMA Long", strategy.long)
    entry_price := close

if short_condition
    strategy.entry("SMA Short", strategy.short)
    entry_price := close

plot(sma_fast, "Fast SMA", color=color.blue)
plot(sma_slow, "Slow SMA", color=color.red)
"""
    code += _pine_footer(sl, tp)
    return code


def _pine_bollinger(period: int = 20, std_dev: float = 2.0,
                    sl: float = 0.03, tp: float = 0.05, **kwargs) -> str:
    code = _pine_header("Bollinger Bands", f"period={period} std={std_dev}", sl, tp)
    code += f"""
bb_period = input.int({period}, "BB Period", minval=5)
bb_std = input.float({std_dev}, "BB Std Dev", minval=0.5, maxval=5, step=0.25)

[middle, upper, lower] = ta.bb(close, bb_period, bb_std)

long_condition = ta.crossover(close, lower)
short_condition = ta.crossunder(close, upper)

if long_condition
    strategy.entry("BB Long", strategy.long)
    entry_price := close

if short_condition
    strategy.entry("BB Short", strategy.short)
    entry_price := close

plot(upper, "Upper", color=color.green)
plot(lower, "Lower", color=color.red)
fill(plot(upper), plot(lower), color=color.new(color.gray, 90))
"""
    code += _pine_footer(sl, tp)
    return code


def _pine_macd(sl: float = 0.03, tp: float = 0.05, **kwargs) -> str:
    code = _pine_header("MACD", "standard 12/26/9", sl, tp)
    code += """
[macd_line, signal_line, _] = ta.macd(close, 12, 26, 9)

long_condition = ta.crossover(macd_line, signal_line)
short_condition = ta.crossunder(macd_line, signal_line)

if long_condition
    strategy.entry("MACD Long", strategy.long)
    entry_price := close

if short_condition
    strategy.entry("MACD Short", strategy.short)
    entry_price := close

plot(macd_line - signal_line, "MACD Hist", color=color.blue, style=plot.style_histogram)
"""
    code += _pine_footer(sl, tp)
    return code


def _pine_donchian(channel_period: int = 20, trend_ema_period: int = 50,
                   sl: float = 0.03, tp: float = 0.05, **kwargs) -> str:
    code = _pine_header("Donchian Channel", f"period={channel_period} ema={trend_ema_period}", sl, tp)
    code += f"""
dc_period = input.int({channel_period}, "Channel Period", minval=5)
ema_period = input.int({trend_ema_period}, "Trend EMA", minval=10)

upper = ta.highest(high, dc_period)
lower = ta.lowest(low, dc_period)
trend_ema = ta.ema(close, ema_period)

long_condition = ta.crossover(close, upper) and close > trend_ema
short_condition = ta.crossunder(close, lower) and close < trend_ema

if long_condition
    strategy.entry("DC Long", strategy.long)
    entry_price := close

if short_condition
    strategy.entry("DC Short", strategy.short)
    entry_price := close

plot(upper, "Upper", color=color.green, linewidth=2)
plot(lower, "Lower", color=color.red, linewidth=2)
plot(trend_ema, "Trend EMA", color=color.orange)
"""
    code += _pine_footer(sl, tp)
    return code


def _pine_atrstop(ema_period: int = 20, atr_period: int = 14, atr_multiplier: float = 2.0,
                  sl: float = 0.03, tp: float = 0.05, **kwargs) -> str:
    code = _pine_header("ATR Stop", f"ema={ema_period} atr={atr_period} mult={atr_multiplier}", sl, tp)
    code += f"""
ema_len = input.int({ema_period}, "EMA Period", minval=5)
atr_len = input.int({atr_period}, "ATR Period", minval=5)
atr_mult = input.float({atr_multiplier}, "ATR Multiplier", minval=0.5, maxval=5, step=0.25)

ema_val = ta.ema(close, ema_len)
atr_val = ta.atr(atr_len)
trail_stop = atr_val * atr_mult

long_condition = close > ema_val and close > close[1] + trail_stop
short_condition = close < ema_val and close < close[1] - trail_stop

if long_condition
    strategy.entry("ATR Long", strategy.long)
    entry_price := close

if short_condition
    strategy.entry("ATR Short", strategy.short)
    entry_price := close

plot(ema_val, "EMA", color=color.blue)
"""
    code += _pine_footer(sl, tp)
    return code


def _pine_kdj(sl: float = 0.03, tp: float = 0.05, **kwargs) -> str:
    code = _pine_header("KDJ", "stochastic oscillator", sl, tp)
    code += """
k_period = input.int(9, "K Period")
d_period = input.int(3, "D Period")
k_smooth = input.int(3, "K Smooth")

k = ta.sma(ta.stoch(close, high, low, k_period), k_smooth)
d = ta.sma(k, d_period)

long_condition = ta.crossover(k, d) and k < 20
short_condition = ta.crossunder(k, d) and k > 80

if long_condition
    strategy.entry("KDJ Long", strategy.long)
    entry_price := close

if short_condition
    strategy.entry("KDJ Short", strategy.short)
    entry_price := close
"""
    code += _pine_footer(sl, tp)
    return code


# ============================================================
# MQL5 导出
# ============================================================

def export_mql5(strategy: str, **params) -> str:
    """导出 MetaTrader 5 Expert Advisor 代码"""
    exporters = {
        "RSI": _mql5_rsi,
        "SMA": _mql5_sma,
        "BOLLINGER": _mql5_bollinger,
        "MACD": _mql5_macd,
    }
    fn = exporters.get(strategy.upper())
    if not fn:
        return f"// 不支持导出 {strategy}（支持: {', '.join(exporters.keys())}）"
    return fn(**params)


def _mql5_header(name: str, sl: float = 0.03, tp: float = 0.05) -> str:
    return f"""//+------------------------------------------------------------------+
//| {name}.mq5 — Auto-generated by Trading System         |
//+------------------------------------------------------------------+
#property copyright "Trading System"
#property version   "1.00"
#property strict

input double StopLoss   = {sl * 100:.1f};    // Stop Loss (%)
input double TakeProfit = {tp * 100:.1f};    // Take Profit (%)
input double LotSize    = 0.01;              // Lot Size

double entryPrice = 0;
"""


def _mql5_rsi(rsi_period: int = 8, oversold: float = 22.0, overbought: float = 75.0,
              sl: float = 0.03, tp: float = 0.05, **kwargs) -> str:
    code = _mql5_header("RSI Strategy", sl, tp)
    code += f"""
input int RSIPeriod   = {rsi_period};
input double Oversold  = {oversold};
input double Overbought = {overbought};

int OnInit() {{ return(INIT_SUCCEEDED); }}

void OnTick() {{
    double rsi = iRSI(_Symbol, PERIOD_CURRENT, RSIPeriod, PRICE_CLOSE, 0);
    double rsiPrev = iRSI(_Symbol, PERIOD_CURRENT, RSIPeriod, PRICE_CLOSE, 1);

    if (rsiPrev <= Oversold && rsi > Oversold) {{
        // Long entry
        entryPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        double sl = entryPrice * (1 - StopLoss / 100);
        double tp = entryPrice * (1 + TakeProfit / 100);
        OrderSend(_Symbol, OP_BUY, LotSize, entryPrice, 3, sl, tp, "RSI Long");
    }}
    else if (rsiPrev >= Overbought && rsi < Overbought) {{
        // Short entry
        entryPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
        double sl = entryPrice * (1 + StopLoss / 100);
        double tp = entryPrice * (1 - TakeProfit / 100);
        OrderSend(_Symbol, OP_SELL, LotSize, entryPrice, 3, sl, tp, "RSI Short");
    }}
}}
"""
    return code


def _mql5_sma(fast_period: int = 10, slow_period: int = 30,
              sl: float = 0.03, tp: float = 0.05, **kwargs) -> str:
    code = _mql5_header("SMA Cross Strategy", sl, tp)
    code += f"""
input int FastMA = {fast_period};
input int SlowMA = {slow_period};

int OnInit() {{ return(INIT_SUCCEEDED); }}

void OnTick() {{
    double smaFast = iMA(_Symbol, PERIOD_CURRENT, FastMA, 0, MODE_SMA, PRICE_CLOSE, 0);
    double smaSlow = iMA(_Symbol, PERIOD_CURRENT, SlowMA, 0, MODE_SMA, PRICE_CLOSE, 0);
    double smaFastPrev = iMA(_Symbol, PERIOD_CURRENT, FastMA, 0, MODE_SMA, PRICE_CLOSE, 1);
    double smaSlowPrev = iMA(_Symbol, PERIOD_CURRENT, SlowMA, 0, MODE_SMA, PRICE_CLOSE, 1);

    if (smaFastPrev <= smaSlowPrev && smaFast > smaSlow) {{
        entryPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        double sl = entryPrice * (1 - StopLoss / 100);
        double tp = entryPrice * (1 + TakeProfit / 100);
        OrderSend(_Symbol, OP_BUY, LotSize, entryPrice, 3, sl, tp, "SMA Long");
    }}
    else if (smaFastPrev >= smaSlowPrev && smaFast < smaSlow) {{
        entryPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
        double sl = entryPrice * (1 + StopLoss / 100);
        double tp = entryPrice * (1 - TakeProfit / 100);
        OrderSend(_Symbol, OP_SELL, LotSize, entryPrice, 3, sl, tp, "SMA Short");
    }}
}}
"""
    return code


def _mql5_bollinger(period: int = 20, std_dev: float = 2.0,
                    sl: float = 0.03, tp: float = 0.05, **kwargs) -> str:
    code = _mql5_header("Bollinger Bands Strategy", sl, tp)
    code += f"""
input int BBPeriod = {period};
input double BBDev  = {std_dev};

int OnInit() {{ return(INIT_SUCCEEDED); }}

void OnTick() {{
    double upper = iBands(_Symbol, PERIOD_CURRENT, BBPeriod, 0, BBDev, PRICE_CLOSE, MODE_UPPER, 0);
    double lower = iBands(_Symbol, PERIOD_CURRENT, BBPeriod, 0, BBDev, PRICE_CLOSE, MODE_LOWER, 0);
    double upperPrev = iBands(_Symbol, PERIOD_CURRENT, BBPeriod, 0, BBDev, PRICE_CLOSE, MODE_UPPER, 1);
    double lowerPrev = iBands(_Symbol, PERIOD_CURRENT, BBPeriod, 0, BBDev, PRICE_CLOSE, MODE_LOWER, 1);

    if (Close[1] <= lowerPrev && Close[0] > lower) {{
        entryPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        double sl = entryPrice * (1 - StopLoss / 100);
        double tp = entryPrice * (1 + TakeProfit / 100);
        OrderSend(_Symbol, OP_BUY, LotSize, entryPrice, 3, sl, tp, "BB Long");
    }}
    else if (Close[1] >= upperPrev && Close[0] < upper) {{
        entryPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
        double sl = entryPrice * (1 + StopLoss / 100);
        double tp = entryPrice * (1 - TakeProfit / 100);
        OrderSend(_Symbol, OP_SELL, LotSize, entryPrice, 3, sl, tp, "BB Short");
    }}
}}
"""
    return code


def _mql5_macd(sl: float = 0.03, tp: float = 0.05, **kwargs) -> str:
    code = _mql5_header("MACD Strategy", sl, tp)
    code += """
int OnInit() { return(INIT_SUCCEEDED); }

void OnTick() {
    double macd = iMACD(_Symbol, PERIOD_CURRENT, 12, 26, 9, PRICE_CLOSE, MODE_MAIN, 0);
    double signal = iMACD(_Symbol, PERIOD_CURRENT, 12, 26, 9, PRICE_CLOSE, MODE_SIGNAL, 0);
    double macdPrev = iMACD(_Symbol, PERIOD_CURRENT, 12, 26, 9, PRICE_CLOSE, MODE_MAIN, 1);
    double signalPrev = iMACD(_Symbol, PERIOD_CURRENT, 12, 26, 9, PRICE_CLOSE, MODE_SIGNAL, 1);

    if (macdPrev <= signalPrev && macd > signal) {
        entryPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        double sl = entryPrice * (1 - StopLoss / 100);
        double tp = entryPrice * (1 + TakeProfit / 100);
        OrderSend(_Symbol, OP_BUY, LotSize, entryPrice, 3, sl, tp, "MACD Long");
    }
    else if (macdPrev >= signalPrev && macd < signal) {
        entryPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
        double sl = entryPrice * (1 + StopLoss / 100);
        double tp = entryPrice * (1 - TakeProfit / 100);
        OrderSend(_Symbol, OP_SELL, LotSize, entryPrice, 3, sl, tp, "MACD Short");
    }
}
"""
    return code
